name = "img"
main = "src/index.ts"
compatibility_date = "2025-08-07"
minify = true
upload_source_maps = true
preview_urls = false
workers_dev = false

[observability]
enabled = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'img'


[images]
binding = "IMAGES"
